apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: dr-vm
  labels:
    drapp: dr-vm
spec:
  instancetype:
    name: u1.medium
  preference:
    name: rhel.9
  running: true
  template:
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: dr-vm-disk
            - disk:
                bus: virtio
              name: cloudinitdisk
      volumes:
        - persistentVolumeClaim:
            claimName: dr-vm-disk
          name: dr-vm-disk
        - cloudInitConfigDrive:
            userData: |
              #cloud-config
              user: cloud-user
              password: rhelpass
              chpasswd:
                expire: false
          name: cloudinitdisk